# Generated by Django 6.0.8 on 2026-09-25 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks",
                to="tasks.task",
                verbose_name="Родительская задача",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("pending", "Не взята в работу"), ("in_progress", "В процессе"), ("done", "Выполнено")],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
