# Generated by Django 6.0.8 on 2026-09-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_parent_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("in_progress", "В процессе"),
                    ("done", "Выполнено"),
                    ("not_taken", "Не взята в работу"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
